FROM sonar-scanner-image:latest AS sonarqube_scan
WORKDIR /app
COPY . .
RUN ls -list
RUN sonar-scanner \
	-Dsonar.host.url="http://localhost:9000" \
	-Dsonar.projectKey="SONAR_PROJECT_KEY" \
	-Dsonar.sources="."
